# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Batarya_Bar = QtWidgets.QLCDNumber(self.centralwidget)
        self.Batarya_Bar.setStyleSheet("background-color: pink;")
        self.Batarya_Bar.setObjectName("Batarya_Bar")
        self.gridLayout.addWidget(self.Batarya_Bar, 1, 2, 1, 1)
        self.Drone_Hiz = QtWidgets.QLCDNumber(self.centralwidget)
        self.Drone_Hiz.setStyleSheet("background-color: blue")
        self.Drone_Hiz.setObjectName("Drone_Hiz")
        self.gridLayout.addWidget(self.Drone_Hiz, 1, 0, 1, 1)
        self.Drone_Yukseklik = QtWidgets.QLCDNumber(self.centralwidget)
        self.Drone_Yukseklik.setStyleSheet("background-color: green; ")
        self.Drone_Yukseklik.setObjectName("Drone_Yukseklik")
        self.gridLayout.addWidget(self.Drone_Yukseklik, 0, 2, 1, 1)
        self.Drone_Denge_Durumu = QtWidgets.QLCDNumber(self.centralwidget)
        self.Drone_Denge_Durumu.setStyleSheet("background-color: #1e7b87;")
        self.Drone_Denge_Durumu.setObjectName("Drone_Denge_Durumu")
        self.gridLayout.addWidget(self.Drone_Denge_Durumu, 0, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdNumber.setStyleSheet("background-color: yellow;")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 0, 1, 1)
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("../../../Downloads/Poyraz_Logo.png"))
        self.Logo.setObjectName("Logo")
        self.gridLayout.addWidget(self.Logo, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
